version: '2'
services:
  main:
    image: nginx
    volumes:
      - ./nginx/nginx-template.conf:/nginx-template.conf
      - ./nginx/.htpasswd:/.htpasswd
      - ./public:/usr/share/nginx/html
      - ./cert:/etc/ssl/certs/
    environment:
      - PROTECTED_HOST=services
      - PROTECTED_HOST_PORT=8080
    ports:
      - 8443:443
    links:
      - services
    command: /bin/bash -c "envsubst < /nginx-template.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  services:
    image: python:3.6
    ports:
      - 8080:8080
    environment:
      - FLASK_DEBUG=1
      - SERVER_PORT=8080
      - PYTHONPATH=$PYTHONPATH:/usr/src/
    volumes:
      - ./requirements.txt:/requirements.txt
      - ./pyroku:/usr/src/pyroku
    command: bash -c "pip install -r /requirements.txt && cd /usr/src/ && python pyroku/server.py"
